ALTER TABLE projects ADD COLUMN IF NOT EXISTS display_order INTEGER DEFAULT 0;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS is_upcoming BOOLEAN DEFAULT FALSE;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS size TEXT DEFAULT 'small';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS link TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS tags TEXT[];
NOTIFY pgrst, 'reload schema';
